name: 1.Deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    name: Update helm image tag
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout config repository
        run: |
          echo "deploy"
